//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artistesta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtistestaEntities : DbContext
    {
        public ArtistestaEntities()
            : base("name=ArtistestaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUCTION> AUCTION { get; set; }
        public virtual DbSet<BIDDER> BIDDER { get; set; }
        public virtual DbSet<COMMENTS> COMMENTS { get; set; }
        public virtual DbSet<FAVORITES> FAVORITES { get; set; }
        public virtual DbSet<FOLLOWER> FOLLOWER { get; set; }
        public virtual DbSet<INTERACTION> INTERACTION { get; set; }
        public virtual DbSet<PUBLISHART> PUBLISHART { get; set; }
        public virtual DbSet<SUPPORT> SUPPORT { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    }
}
