//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artistesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLLOWER
    {
        public long FID { get; set; }
        public Nullable<int> FOLLOWERID { get; set; }
        public Nullable<int> FOLLOWINGID { get; set; }
        public string DATE { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
