//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artistesta.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.UI.WebControls;

    public partial class PUBLISHART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUBLISHART()
        {
            this.BIDDER = new HashSet<BIDDER>();
            this.COMMENTS = new HashSet<COMMENTS>();
            this.FAVORITES1 = new HashSet<FAVORITES>();
            this.INTERACTION = new HashSet<INTERACTION>();
        }
    
        public long ARTID { get; set; }
        public Nullable<int> USERID { get; set; }
        [Required(ErrorMessage = "Field Cannot Be Empty")]
        public string INSPIRATION { get; set; }
        public string ARTWORK { get; set; }
        [Required(ErrorMessage = "Field Cannot Be Empty")]
        public string TITLE { get; set; }
        public string TIME { get; set; } = DateTime.Now.ToString();
        [Required(ErrorMessage = "<br> Choose a category")]
        public string CATEGORY { get; set; }
        public Nullable<long> ENCOURAGES { get; set; }
        public Nullable<long> DISCOURAGES { get; set; }
        public Nullable<long> FAVORITES { get; set; }
        public Nullable<bool> ISPINNED { get; set; }
        public bool FORSALE { get; set; }
        public string MINIMUMBID { get; set; }
        public string AUCTIONID { get; set; }
        public string CURHIGHESTBID { get; set; }
        public string CURBIDDERID { get; set; }
        public string STATUS { get; set; } = "Pending";

        public HttpPostedFileBase File { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIDDER> BIDDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTS> COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORITES> FAVORITES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERACTION> INTERACTION { get; set; }
        public virtual USER USER { get; set; }



    }
    public enum cats
    {
        ABSTRACT,
        ANIMALS,
        ANIME,
        ARCHITECTURE,
        AUTOMOBILE,
        BLACKandWHITE,
        CITYSCAPE,
        GAMES,
        ILLUSTRATION,
        MISC,
        NATURE,
        OBJECTS,
        PORTRAIT,
        SKETCH,
        SUPERHERO,
        CALLIGRAPHY
    }
}
